language: node_js
node_js:
  - 11.13.0
script:
  - npm install --global workbox-cli
  - workbox generateSW workbox-config.js
  - mv index.html ./public/index.html
  - mv -v assets ./public/
deploy:
  - provider: firebase
    token: $FIREBASE_TOKEN
    project: stasbreadless-bsa20-homepage
    on:
      branch: master
  - provider: firebase
    token: $FIREBASE_TOKEN
    project: breadless-bsa-homepage-dev
    on:
      branch: develop